apiVersion: v2
name: scenario-management-service
description: Helm chart for the Scenario Management Service in the Smart Home System

type: application

version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "15.5.20"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: postgresql.enabled
