replicaCount: 2

image:
  repository: my-docker-repo/notification-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8085

env:
  SPRING_PROFILES_ACTIVE: prod
  KAFKA_BROKER_URL: kafka:9092

resources: {}
