@startuml
title SmartHome Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "Владелец системы умного дома")
System(SmartHomeSystem, "SmartHome System", "Система управления умным домом")

System_Ext(system, "Heating System", "External system for handling home")

Rel(user, SmartHomeSystem, "Uses the system")
Rel(SmartHomeSystem, system, "Handling home")

@enduml