@startuml
title SmartHome Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "Владелец системы умного дома")
System(SmartHomeSystem, "SmartHome System", "Система управления умным домом", "Monolith (Spring Boot, PostgreSQL)")

Container(webApp, "Web Application", "Web App", "React.js")
Container(mobileApp, "Mobile App", "Mobile App", "Flutter")

System_Ext(heatingSystem, "Heating System", "External system for handling home", "Производитель оборудования")

Rel(user, webApp, "Использует", "HTTPS")
Rel(user, mobileApp, "Использует", "HTTPS")
Rel(webApp, SmartHomeSystem, "Отправляет запросы", "REST API (HTTPS)")
Rel(mobileApp, SmartHomeSystem, "Отправляет запросы", "REST API (HTTPS)")
Rel(SmartHomeSystem, heatingSystem, "Обрабатывает управление отоплением", "Протокол производителя (например, MQTT или проприетарный драйвер)")

@enduml
