apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api-gateway-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api-gateway
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api-gateway
    spec:
      containers:
          - name: api-gateway
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            ports:
              - containerPort: 8080
            env:
              - name: SPRING_PROFILES_ACTIVE
                value: "{{ .Values.env.SPRING_PROFILES_ACTIVE }}"
              - name: KAFKA_BROKER_URL
                value: "{{ .Values.env.KAFKA_BROKER_URL }}"
              - name: API_GATEWAY_PORT
                value: "{{ .Values.env.API_GATEWAY_PORT }}"
