replicaCount: 2

image:
  repository: my-docker-repo/scenario-management-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8083

env:
  SPRING_PROFILES_ACTIVE: prod
  DATABASE_URL: postgresql://user:password@postgres:5432/scenario_db

resources: {}
