apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-device-management-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-device-management
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-device-management
    spec:
      containers:
          - name: device-management
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            ports:
              - containerPort: 8082
            env:
              - name: SPRING_PROFILES_ACTIVE
                value: "{{ .Values.env.SPRING_PROFILES_ACTIVE }}"
              - name: KAFKA_BROKER_URL
                value: "{{ .Values.env.KAFKA_BROKER_URL }}"
              - name: DATABASE_URL
                value: "{{ .Values.env.DATABASE_URL }}"
