version: "3"

services:
  elasticsearch:
    image: elasticsearch:8.14.3
    volumes:
      - ./conf/elasticsearch/conf.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx1G"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "sampleELK"
      discovery.type: single-node
    networks:
      - elknet
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    image: logstash:8.14.3
    volumes:
      - ./conf/logstash/conf.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./conf/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./conf/logstash/pipelines:/usr/share/logstash/config/pipelines:ro
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    ports:
      - "5044:5044"
      - "5010:5000"
      - "9600:9600"
    networks:
      - elknet
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.14.3
    depends_on:
      - elasticsearch
    volumes:
      - ./conf/kibana/conf.yml:/usr/share/kibana/config/kibana.yml:ro
    networks:
      - elknet
    ports:
      - "5601:5601"

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./var/log/nginx:/var/log/nginx
    networks:
      - elknet
    ports:
      - 80:80

  beats:
    image: elastic/filebeat:8.14.3
    volumes:
      - ./conf/filebeat/conf.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./var/log/nginx:/var/log/nginx
    networks:
      - elknet
    depends_on:
      - nginx
      - elasticsearch

networks:
  elknet:
    driver: bridge
