apiVersion: v2
name: smart-home-system
description: A Helm chart for deploying Smart Home System services

type: application

version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: kafka
    version: "2.5.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: kafka.enabled
  - name: postgresql
    version: "15.5.20"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: postgresql.enabled
