replicaCount: 2

image:
  repository: my-docker-repo/api-gateway
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  SPRING_PROFILES_ACTIVE: prod
  KAFKA_BROKER_URL: kafka:9092
  API_GATEWAY_PORT: 8080

resources: {}
