apiVersion: v2
name: telemetry-service
description: Helm chart for the Telemetry Service in the Smart Home System

type: application

version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: kafka
    version: "2.5.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: kafka.enabled
